services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-http://localhost:3000}
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: file:/data/.db
      UPLOAD_DIR: /data/files
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL:-http://localhost:3000}
    volumes:
      - hub-data:/data

volumes:
  hub-data:
