export const theme = {
  colors: {
    content: {
      primary: '#2b3b47',
      muted: '#5a6b76',
      inverse: '#ffffff',
      accent: '#14516d',
    },
    surface: {
      paper: '#eef4f5',
      raised: '#ffffff',
      brand: '#14516d',
      canvas: '#67aab5',
      ink: '#2b3b47',
      gold: '#ffca00',
      wash: '#d7ecef',
    },
    border: {
      subtle: '#c5d6db',
      strong: '#14516d',
    },
    status: {
      published: '#14516d',
      review: '#c99700',
      returned: '#8f3d2b',
      invited: '#14516d',
      public: '#3d7a84',
    },
    overlay: {
      start: 'rgba(43, 59, 71, 0.82)',
      mid: 'rgba(20, 81, 109, 0.42)',
      end: 'rgba(20, 81, 109, 0.08)',
    },
    focus: {
      ring: 'rgba(20, 81, 109, 0.24)',
    },
  },
  typography: {
    fontFamily: {
      sans: "var(--font-onest), 'Helvetica Neue', sans-serif",
    },
    fontSizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      body: '1.1rem',
      lg: '1.125rem',
      nav: '1.125rem',
      button: '1rem',
      lead: '1.25rem',
      xl: '1.5rem',
      xxl: '2.25rem',
      statement: '2.2rem',
      section: '2.35rem',
      panel: '2.5rem',
      display: '3.25rem',
      hero: 'clamp(2.5rem, 4.6vw, 4.25rem)',
      stat: 'clamp(2.5rem, 5vw, 4rem)',
    },
    fontWeights: {
      regular: 400,
      medium: 500,
      bold: 700,
    },
    lineHeights: {
      tight: 1.1,
      statement: 1.3,
      body: 1.7,
    },
    letterSpacing: {
      tight: '-0.03em',
      wide: '0.1em',
    },
  },
  spacing: (units: number) => `${units * 4}px`,
  radii: {
    none: '0',
    sm: '2px',
  },
  layout: {
    maxWidth: '80rem',
    wideMaxWidth: '90rem',
    gutter: '1.5rem',
    gutterWide: '2.5rem',
    asideWidth: '24rem',
    previewHeight: '32rem',
    logoWidth: 172,
    logoWidthMobile: 120,
    logoHeight: 108,
    authPhotoRatio: '1.15fr',
    authFormWidth: '28rem',
    curveHeight: '5.5rem',
    curveClip: 'ellipse(70% 100% at 50% 100%)',
    authMobilePhoto: '14rem',
    heroPhotoHeight: '36rem',
    bannerHeight: '2.75rem',
    areaMin: '8rem',
    ctaBorder: '0.25rem',
    revealLift: '1.25rem',
    heroZoom: 1.06,
    menuWidth: '100%',
    dropdownMin: '16rem',
    sheetMin: '10in',
    letterHeight: '11in',
    letterWidth: '8.5in',
    shotHeight: '1.7in',
    featurePhoto: '22rem',
    footerIconGap: '1.25rem',
  },
  zIndex: {
    base: 0,
    overlay: 1,
    content: 2,
    nav: 10,
    menu: 20,
  },
  motion: {
    marquee: '42s',
    fade: '160ms',
    easing: 'linear',
    out: 'ease-out',
    reveal: '700ms',
    stagger: '80ms',
    emphasize: 'cubic-bezier(0.22, 1, 0.36, 1)',
    count: '1200ms',
    zoom: '18s',
    page: '280ms',
    text: '520ms',
  },
  opacity: {
    disabled: 0.45,
    hidden: 0,
  },
  icons: {
    sm: 16,
    md: 20,
    lg: 28,
    xl: 48,
  },
  breakpoints: {
    md: '48rem',
    lg: '80rem',
  },
  observe: {
    reveal: 0.16,
    count: 0.4,
  },
} as const

export type AppTheme = typeof theme
